### ISSUE TITLE
Fix book listing book cell size in mobile view

### ISSUE THREAD

**Issue by omaralbeik** [omaralbeik/omaralbeik.com#70]
![screen shot 2017-10-11 at 23 50 58](https://user-images.githubusercontent.com/8127757/31466220-24ce2a84-aedf-11e7-97a1-1cb8ff89244e.jpg)

**Comment by lionbytes** [comment]
**Book Link** CSS selector in Phone view must be edited as follows: 
```
.book-listing li > a {
    height: 185px;
    width: 120px;
    overflow: hidden;
}
```
Fix has been applied to HTML version and will be pushed soon.

**Comment by omaralbeik** [comment]
Thank you @lionbytes 
I tried updating the css, looks like they are still miss-aligned
![screen shot 2017-10-15 at 19 22 57](https://user-images.githubusercontent.com/8127757/31586776-6138a344-b1de-11e7-8e18-727271e34085.jpg)

**Comment by omaralbeik** [comment]
Thanks @lionbytes 🎉

**Comment by lionbytes** [comment]
Welcome welcome ✋
